### ISSUE TITLE
R8G3 TUNGKU Penyesuaian

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#20]
![Image](https://github.com/user-attachments/assets/af774bd2-f356-4fb9-9110-ba429a8fbb6e)

TUNGKU R8 G3 (Ubah Sesuaikan)
- Dustfall : Rebirth 
Biaya Pembuatan 100jt (Senjata)
Biaya Pembuatan 35jt (Armor)

- Dustfall : Allteration
Biaya pembuatan 5jt (Senjata)
Biaya Pembuatan 3jt (Armor)

- Dustfall : Purification
Biaya Pembuatan 5jt (Senjata)
Biaya Pembuatan 3jt (Armor)

- Dustfall : Spirit of the forge
Biaya pembuatan 8jt (Senjata)
Biaya Pembuatan 5jt (Armor)

**Comment by hrace009** [comment]
Done
