### ISSUE TITLE
LABIRIN (QUICK MAZE)

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#23]
Dungeon : Quick Maze Lv100
Npc : Thunderdrum

- Syarat : Hapuskan Requirement masuk (persyaratan wibawa , LV , dan mirage)
- Bos di dalam goa official spirit harus ada untuk tahan damage Bos , Kurangi Damage Semua bos 40-50% (karena kita tanpa spirit)

**Comment by hrace009** [comment]
Check Dream Space

**Comment by hrace009** [comment]
All Mobs Att + MAtt Reduce 50%

Next, tolong di cek untuk running quicsand maze

**Comment by Gusv34** [comment]
Cek NPC Dreamspace (Quest Quicksand Maze (Party Mode) , ketua PT tidak dapat quest , cek syaratnya
