### ISSUE TITLE
SUMBER REPUTASI

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#24]
SUMBER REPUTASI

- Tungku Perfect World Classic Indonesia
1 Warsong Emblem = 1 Wraith officer Badge (Ubah resep -Produksi Bag.Cool)

- Mailbox -Celestial Exchange (Bag.PWCI)
1 Celestial Insignia = 1 Wraith officer Badge
3 Celestial shard = 1 Wraith officer Badge

-Tungku Cauldron of Contemplation (Award exchange)
3 Supply Token = 1 Wraith officer Badge

**Comment by hrace009** [comment]
1 Warsong Emblrm = 1 Wraith Office Badge
![Image](https://github.com/user-attachments/assets/03966fe1-326b-4cd5-8fa5-deb210af1675)

10 Supply Token = 1 Wraith officer Badge
![Image](https://github.com/user-attachments/assets/2926551a-bed8-4338-a82a-91353e2b168f)

**Comment by hrace009** [comment]
NEXT:

Mailbox -Celestial Exchange (Bag.PWCI)
1 Celestial Insignia = 1 Wraith officer Badge
3 Celestial Insignia = 1 Wraith officer Badge

yang benar yang mana?

**Comment by hrace009** [comment]
![Image](https://github.com/user-attachments/assets/d2765490-7187-459d-b5d1-5f468ee5073b)
All Done
