### ISSUE TITLE
Thursday Night Fight Merchant

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#27]
Thursday Night Fight Merchant 
Tambahkan di bagian Winner =

Token of Valiancy (2) + Token of Might (10) = 1 Garnet Gem
Token of Valiancy (2) + Token of Might (10) = 1 Sapphire Gem
Token of Valiancy (2) + Token of Might (10) = 1 Citrine Gem
Token of Valiancy (2) + Token of Might (10) = 1 Amber Gem 
Token of Valiancy (2) + Token of Might (10) = 1 Turquoise Gem 
1 Token of Might = 2 Wraith officer Badge
1 Token of Valiancy = 3 Wraith officer Badge
Token of Valiancy (2) + Token of Might (10) = 50 Spirit Chisel  
Token of Valiancy (1) = 15 Spirit Chisel  
Token of Might (10) = 5 Spirit Chisel

**Comment by hrace009** [comment]
![Image](https://github.com/user-attachments/assets/f2cc9651-2288-4cd1-ad19-5265716147e4)
Done
