### ISSUE TITLE
Auction (item Mall)

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#29]
Item yang dijual, sesuaikan dengan versi (Check)

**Comment by Gusv34** [comment]
Item bid Lelang
Start Bid jadikan = 50 Coin
Yang di Ubah hanya :

39926	100	7200	归星盘礼盒 = 47284 (Pet)
46463	100	7200	祭月礼月仙之券 = 44000
46464	100	7200	彩云障月月仙之券 = 44001
46465	100	7200	神镰伐桂月仙之券 = 43889
46466	100	7200	落月击月仙之券 = 43999
46467	100	7200	玉嫦息月仙之券 = 47927
46468	100	7200	啸月夜影之券 = 47923
46469	100	7200	影噬夜影之券= 47895
46470	100	7200	影遁夜影之券 = 48310
46471	100	7200	影飞绝夜影之券= 48689
46472	100	7200	贪狼刃夜影之券= 50611

**Comment by hrace009** [comment]
Done All Replace
