### ISSUE TITLE
FWP ORDER PWCI (NPC)

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#33]
NPC FWP

FWP ORDER PWCI (Npc FWP)
Semua Resep = 1 FWP Token PWCI  + 5 Jt gold 

List Fwp :
48190
48191
50905
50906
50901
50902
43644
43646
43651
43652
48194
48195
48196
48197
50991
50992
57890
57891
39716
39717
46953
46954
58336
58335
47664
47663
50994
50995
50904
50903

**Comment by hrace009** [comment]
Done,
New NPC Spawned at Archosaur City
![Image](https://github.com/user-attachments/assets/288d187a-db9d-420e-bf26-a73a8a1b3173)
