### ISSUE TITLE
LABIRIN QUICK SAND MAZE

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#41]
LABIRIN

- Hilangkan Syarat masuk Labirin Quick Sand
-  1 RC 1 UC + 1jt gold = 1 Quicksand Smokewisp (Tungku PWCI)
- Damage semua bos Quicksand 100 -50%
- Bos labirin pakai bahasa china (ubah english/indo) tidak bisa di kill harus sesuai instruksi

**Comment by hrace009** [comment]
- Hilangkan Syarat masuk Labirin Quick Sand :white_check_mark:
-  1 RC 1 UC + 1jt gold = 1 Quicksand Smokewisp (Tungku PWCI) :white_check_mark:
- Damage semua bos Quicksand 100 -50% :white_check_mark:
- Bos labirin pakai bahasa china (ubah english/indo) tidak bisa di kill harus sesuai instruksi

**Comment by hrace009** [comment]
Done
