### ISSUE TITLE
Jewelcrafment Npc

### ISSUE THREAD

**Issue by Gusv34** [hrace009/Perfect-World-Classic-Indonesia#47]
Jewelcrafment :

Tambahkan
Bag.Power (Tambahkan)
3 Diamond of tiger = 1 Diamond of Dragon

Ubah 
Bag.Power
9 Diamond of TIger = 1 Deity Stone

**Comment by hrace009** [comment]
![Image](https://github.com/user-attachments/assets/c25c9648-9bf1-4c59-b29b-865bb8ae6684)
DONE
